"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from system.utils import get_app_dir
#import environ

QT_MULTI = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DB_DIR = BASE_DIR
if getattr(sys, "frozen", False):
    DB_DIR = get_app_dir()

#DEFAULT_FILE_STORAGE = 'tenant_schemas.storage.TenantFileSystemStorage'



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v6sgsip42w7-7fci68grkxaq+v0&ut)z)9zizaa443j!)y0p9t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    #'tenant_schemas',
    #'account',
    'system',
    'activities.apps.ActivitiesConfig',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    #'django.contrib.sessions',
    #'django.contrib.messages',
    #'django.contrib.staticfiles',
]

MIDDLEWARE = [
    #'tenant_schemas.middleware.TenantMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #SessionUserTenantMiddlewareによるテナント名称の取得には、認証されたユーザIDが必要なので、
    #AuthenticationMiddlewareの後に呼ばれるようにする
    #'account.middleware.SessionUserTenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'
#PUBLIC_SCHEMA_URLCONF = 'backend.account.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR / 'db.sqlite3',
    }
#    'default': {
#         'ENGINE': 'tenant_schemas.postgresql_backend',
#         'NAME': QT_DB_NAME,
#         'USER': QT_DB_USER,
#         'PASSWORD': QT_DB_PASSWORD,
#         'HOST': "",
#         'PORT': "",
#    }
}


#DATABASE_ROUTERS = (
#    'tenant_schemas.routers.TenantSyncRouter',
#)

USE_POSTGRESQL = False



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = (
    BASE_DIR.joinpath('frontend'),  # new
    #BASE_DIR.joinpath('frontend','static'),  # new
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ログインと、セッション認証のための設定

#AUTH_USER_MODEL = "account.QtUser"

#CSRF_COOKIE_SAMESITE = 'Strict'
#SESSION_COOKIE_SAMESITE = 'Strict'
#CSRF_COOKIE_HTTPONLY = False
#SESSION_COOKIE_HTTPONLY = True
#CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']

#ログイン後、リダイレクトするURL
LOGIN_REDIRECT_URL = ''    # 追加
#LOGOUT_REDIRECT_URL ='/qt/account/loginHome'
#DEBUG = True

#ログの設定

def get_log_file():
    if getattr(sys, 'frozen', False):
        # PyInstallerで実行されている場合
        if sys.platform == "darwin":
            log_dir = Path.home() / "Library/Application Support/Quality-Work/logs"
        elif sys.platform == "win32":
            log_dir = Path(os.getenv("LOCALAPPDATA")) / "Quality-Work/logs"
    else:
        # 通常のスクリプト実行の場合
        base_dir = Path(__file__).parent.parent
        log_dir = base_dir / "logs"

    # フォルダが存在しない場合は作成
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir / "server.log"

LOG_FILE = get_log_file()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # ログ出力フォーマットの設定
    'formatters': {
        'production': {
            'format': '%(asctime)s - %(name)s:%(lineno)d - %(levelname)s - %(message)s'
        },
    },
    # ハンドラの設定
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_FILE,
            'formatter': 'production',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 7,
        },
    },
    # ロガーの設定
    'loggers': {
        # Django自身が出力するログ全般を拾うロガー
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },

    },
}
