# Generated by Django 5.0.2 on 2024-10-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_fileupdatehistory_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupdatehistory',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='fileupdatehistory',
            name='contents',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
