# Generated by Django 5.0.2 on 2024-10-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_fileupdatehistory_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupdatehistory',
            name='contents',
            field=models.FileField(upload_to='.'),
        ),
    ]
