# Generated by Django 5.1.2 on 2025-04-09 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_fileupdatehistory_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField(unique=True)),
                ('duration', models.IntegerField()),
                ('start_app', models.CharField(max_length=128)),
                ('start_title', models.CharField(max_length=256)),
                ('longest_app', models.CharField(max_length=128)),
                ('longest_title', models.CharField(max_length=256)),
                ('another_app', models.CharField(default=None, max_length=128)),
                ('another_title', models.CharField(default=None, max_length=256)),
                ('selected', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
    ]
