# Generated by Django 5.1.2 on 2025-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_audioactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioactivity',
            name='another_app',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='audioactivity',
            name='another_title',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='audioactivity',
            name='longest_app',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='audioactivity',
            name='longest_title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
