# Generated by Django 5.1.2 on 2025-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_audioactivity_another_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioactivity',
            name='selected',
        ),
        migrations.AddField(
            model_name='audioactivity',
            name='show_front',
            field=models.BooleanField(default=True),
        ),
    ]
