# Generated by Django 5.1.2 on 2025-04-18 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_remove_audioactivity_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioactivity',
            name='selected',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
