# Generated by Django 5.1.2 on 2025-04-22 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_audioactivity_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioactivity',
            name='show_front',
        ),
        migrations.AddField(
            model_name='audioactivity',
            name='show_policy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
