# Generated by Django 5.1.2 on 2025-04-23 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_remove_audioactivity_show_front_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='default', max_length=32)),
                ('audio_activity_policy', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('duration_threshold', models.IntegerField(default=10)),
                ('strokes_threshold', models.IntegerField(default=10)),
                ('distance_threshold', models.IntegerField(default=1000)),
            ],
        ),
    ]
