# Generated by Django 5.1.2 on 2025-08-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_systemsettings_audio_activity_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('name', models.CharField(max_length=128, null=True)),
                ('created_dtime', models.DateTimeField()),
                ('num_of_labels', models.IntegerField()),
                ('num_of_learning_data', models.IntegerField()),
                ('score', models.CharField(max_length=4096, null=True)),
                ('using', models.BooleanField()),
            ],
        ),
    ]
