# Generated by Django 5.1.2 on 2025-09-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_activitypredictor'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypredictor',
            name='data_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activitypredictor',
            name='data_start',
            field=models.DateTimeField(null=True),
        ),
    ]
