# Generated by Django 5.1.2 on 2025-09-21 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activitypredictor_data_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='perspective',
            name='index',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
