# Generated by Django 5.1.2 on 2025-09-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_category_index_perspective_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedActivityEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_activities', to='activities.category')),
            ],
        ),
    ]
