# Generated by Django 5.1.2 on 2025-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=128)),
                ('uploadTime', models.DateTimeField()),
                ('contents', models.FileField(upload_to='.')),
                ('status', models.CharField(max_length=128)),
            ],
        ),
    ]
